resources:
  - name: grafana-paas-git
    type: git
    source:
      uri: https://github.com/alphagov/grafana-paas
      branch: master

  - name: deploy-to-paas-prometheus-grafana-space
    type: cf
    source:
      api: https://api.cloud.service.gov.uk
      username: ((cf_user))
      password: ((cf_password))
      organization: gds-tech-ops
      space: prometheus-grafana

jobs:
  - name: update-pipeline
    serial: true
    plan:
      - get: grafana-paas-git
        trigger: true
      - set_pipeline: grafana
        file: grafana-paas-git/pipeline.yml
  - name: deploy-grafana-to-paas
    serial: true
    plan:
      - get: grafana-paas-git
        trigger: true
        passed: [update-pipeline]
      - put: deploy-to-paas-prometheus-grafana-space
        params:
          manifest: grafana-paas-git/manifest.yml
          show_app_log: true
