name: Release Grafana

on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # 2.4.0
      - name: add-cloudfoundry-repository
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        
      - name: install-system-dependencies
        run: |        
          sudo apt-get update
          sudo apt-get install -y cf7-cli
          
      - name: deploy-to-paas
        env:
          CF_USERNAME: ${{ secrets.CF_EMAIL }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_DOCKER_PASSWORD: ${{ secrets.CF_DOCKER_PASSWORD }}
        run: | 
          cf api https://api.cloud.service.gov.uk 
          cf auth
          cf target -o gds-tech-ops -s prometheus-grafana

          cf push -f ./manifest.yml --strategy rolling
